version: '3.3'

services:

  gost-db-dump:
    image: "postgres:10"
    volumes:
      - "./dumps:/monica/dumps"
      - "./dump_gost_db.sh:/monica/dump_gost_db.sh"
    environment:
      - GOST_DB_HOST=mpclfdbpql01.monica-cloud.eu
      - GOST_DB_PORT=5432
      - GOST_DB=gost_woodstower
      - GOST_DB_USER=monica_accou
      - GOST_DB_PASSWORD=??????
    command: ["/monica/dump_gost_db.sh"]

  gost-db:
    image: "geodan/gost-db"
    restart: always
    ports:
      - 5432:5432     
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./dumps:/monica/dumps"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=gost

  mosquitto:
    image: "eclipse-mosquitto"
    ports:
      - 1883:1883

  gost:
    image: geodan/gost
    depends_on:
      - gost-db
      - mosquitto
    environment:
      GOST_DB_HOST: gost-db
      GOST_SERVER_EXTERNAL_URI: http://localhost:8080/
      GOST_MQTT_HOST: mosquitto
      GOST_MQTT_PORT: 1883
      GOST_MQTT_CLIENTID: gost
      GOST_MQTT_PREFIX: GOST
      GOST_SERVER_MAX_ENTITIES: 1000
      GOST_LOG_VERBOSE_FLAG: "true"
      GOST_MQTT_VERBOSE: "true"

  gost-dashboard:
    image: geodan/gost-dashboard
    ports:
      - "8080:8080"
    depends_on:
      - gost

volumes:
  pgdata: